"""Sweep extreme-noise levels to find profile-specific tap-out boundaries."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean


def run_probe(
    *,
    mode: str,
    profile: str,
    seed: int,
    noise_scale: float,
    trials: int,
) -> dict[str, object]:
    tag = f"tapout-{profile}-noise-{noise_scale:g}-seed-{seed}".replace(".", "p")
    cmd = [
        sys.executable,
        "scripts/compare_inferred_stress_routing.py",
        "--mode",
        mode,
        "--tolerance-profile",
        profile,
        "--seed",
        str(seed),
        "--trials",
        str(trials),
        "--extreme-noise-scale",
        str(noise_scale),
        "--output-tag",
        tag,
    ]
    subprocess.run(cmd, check=True)
    path = Path(f"docs/inferred-stress-routing-{mode}-{tag}.json")
    return json.loads(path.read_text(encoding="utf-8"))


def write_summary(summary: dict[str, object], output_path: Path) -> None:
    lines = [
        "# Tap-Out Boundary Sweep Summary",
        "",
        "This sweep increases extreme out-of-distribution noise to find where each tolerance profile taps out.",
        "",
        "## Setup",
        "",
        f"- Mode: `{summary['mode']}`",
        f"- Device: `{summary['device_name']}`",
        f"- Profiles: `{', '.join(summary['profiles'])}`",
        f"- Seeds: `{', '.join(str(seed) for seed in summary['seeds'])}`",
        f"- Noise scales: `{', '.join(str(value) for value in summary['noise_scales'])}`",
        "",
        "## Boundary Table",
        "",
        "| Profile | First tap-out noise | First zero-failure noise | Max no-tapout noise | Final tap-out mean | Final tap-out failure mean |",
        "| :--- | ---: | ---: | ---: | ---: | ---: |",
    ]

    for profile in summary["profiles"]:
        p = summary["profile_summary"][profile]
        lines.append(
            f"| {profile} | {p['first_tapout_noise']} | {p['first_zero_failure_noise']} | "
            f"{p['max_no_tapout_noise']} | {p['final_tapout_rate_mean']} | "
            f"{p['final_tapout_failure_rate_mean']} |"
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "The sweep separates intensity tolerance from safety. A profile can tolerate more unfamiliar noise before tapping out, but if it never taps out it can preserve failures at higher noise levels.",
            "",
            "## Boundary",
            "",
            "This is synthetic mechanism evidence. Noise is generated by the harness, and the OOD estimator is hand-built.",
            "",
        ]
    )
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["plugged", "demo"], default="plugged")
    parser.add_argument("--profiles", default="low-tolerance,standard,high-intensity")
    parser.add_argument("--seeds", default="14,21,42")
    parser.add_argument("--noise-scales", default="0.8,1.2,1.6,2.0,2.4,2.8,3.2,3.6,4.0")
    parser.add_argument("--trials", type=int, default=100)
    args = parser.parse_args()

    profiles = [value.strip() for value in args.profiles.split(",") if value.strip()]
    seeds = [int(value.strip()) for value in args.seeds.split(",") if value.strip()]
    noise_scales = [float(value.strip()) for value in args.noise_scales.split(",") if value.strip()]

    rows = []
    for profile in profiles:
        for noise_scale in noise_scales:
            seed_runs = [
                run_probe(
                    mode=args.mode,
                    profile=profile,
                    seed=seed,
                    noise_scale=noise_scale,
                    trials=args.trials,
                )
                for seed in seeds
            ]
            rows.append(
                {
                    "profile": profile,
                    "noise_scale": noise_scale,
                    "tapout_rate_mean": round(mean(run["tapout_rate"] for run in seed_runs), 8),
                    "inferred_failure_rate_mean": round(
                        mean(run["comparison"]["inferred_failure_rate"] for run in seed_runs),
                        8,
                    ),
                    "tapout_failure_rate_mean": round(
                        mean(run["comparison"]["tapout_failure_rate"] for run in seed_runs),
                        8,
                    ),
                    "tapout_vs_inferred_mean": round(
                        mean(run["comparison"]["tapout_vs_inferred_overall"] for run in seed_runs),
                        8,
                    ),
                }
            )

    profile_summary = {}
    for profile in profiles:
        selected = [row for row in rows if row["profile"] == profile]
        first_tapout = next((row["noise_scale"] for row in selected if row["tapout_rate_mean"] > 0.0), None)
        first_zero_failure = next((row["noise_scale"] for row in selected if row["tapout_failure_rate_mean"] == 0.0), None)
        no_tapouts = [row["noise_scale"] for row in selected if row["tapout_rate_mean"] == 0.0]
        final = selected[-1]
        profile_summary[profile] = {
            "first_tapout_noise": first_tapout,
            "first_zero_failure_noise": first_zero_failure,
            "max_no_tapout_noise": max(no_tapouts) if no_tapouts else None,
            "final_tapout_rate_mean": final["tapout_rate_mean"],
            "final_tapout_failure_rate_mean": final["tapout_failure_rate_mean"],
        }

    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mode": args.mode,
        "device_name": "NVIDIA GeForce RTX 4050 Laptop GPU" if args.mode == "plugged" else "CPU",
        "profiles": profiles,
        "seeds": seeds,
        "noise_scales": noise_scales,
        "rows": rows,
        "profile_summary": profile_summary,
    }

    json_path = Path(f"docs/tapout-boundary-sweep-{args.mode}.json")
    md_path = Path("docs/tapout-boundary-sweep-summary.md")
    json_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    write_summary(summary, md_path)
    print(json.dumps(profile_summary, indent=2))
    print(f"wrote={json_path}")
    print(f"wrote={md_path}")


if __name__ == "__main__":
    main()
